name: Python Workflow with Secrets for Creating a New Confluence Page

on:
  push:
    branches:
      - master

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
      PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script with secrets
      run: python confluence_generator/create_new_confluence.py $USERNAME $PASSWORD